
return {
  { import = "plugins.ai" },
  { import = "plugins.completion" },
  { import = "plugins.core" },
  { import = "plugins.dap" },
  { import = "plugins.editing" },
  { import = "plugins.folding" },
  { import = "plugins.fun" },
  { import = "plugins.git" },
  { import = "plugins.integration" },
  { import = "plugins.langs" },
  { import = "plugins.lsp.configs" },
  { import = "plugins.navigation" },
  { import = "plugins.sessions" },
  { import = "plugins.terminal" },
  { import = "plugins.testing" },
  { import = "plugins.ui" },
  { import = "plugins.writing" },
  { import = "plugins.database" },
}
